# Common stuff

theme:
  name: 'material'
markdown_extensions:
  - codehilite
use_directory_urls: false
repo_url: https://github.com/uliska/lilyponds-scheme/

# Subbook specific stuff
site_dir: ../site
edit_uri: edit/master/introduction/docs
site_name: LilyPond's Scheme
nav:
  - Introduction:
    - Home: index.md
    - "LilyPond's Scheme": 'lilyponds-scheme.md'
    - 'Learning the Language': 'language.md'
    - 'Integrating in LilyPond': 'integrating.md'
    - 'Advanced Interaction': 'advanced.md'
  - 'Scheme ⬊': 'scheme/index.html'
  - 'Scheme in LilyPond ⬊': 'lilypond/index.html'
  - 'LilyPond Internals ⬊': 'internals/index.html'
#  - 'License': 'license.md'
